/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.weber.cs3230.projects.finalproject;

import java.awt.Color;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author zycmm
 */
public class AddCustomerDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddCustomerDialog
     */
    public AddCustomerDialog(java.awt.Frame parent, boolean modal, List<Customer> customers) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.customers = customers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        initBalanceLabel = new javax.swing.JLabel();
        initBalanceTextField = new javax.swing.JTextField();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeComboBox = new javax.swing.JComboBox<>();
        addCustomerOKButton = new javax.swing.JButton();
        addCustomerCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Customer Dialog");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel);

        firstNameTextField.setText("John");
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameTextField);

        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel);

        lastNameTextField.setText("Doe");
        getContentPane().add(lastNameTextField);

        phoneNumberLabel.setText("Phone Number:");
        getContentPane().add(phoneNumberLabel);

        phoneNumberTextField.setText("8015551234");
        getContentPane().add(phoneNumberTextField);

        initBalanceLabel.setText("Initial Balance");
        getContentPane().add(initBalanceLabel);

        initBalanceTextField.setText("1000");
        getContentPane().add(initBalanceTextField);

        accountTypeLabel.setText("Account Type");
        getContentPane().add(accountTypeLabel);

        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings", "Investment" }));
        getContentPane().add(accountTypeComboBox);

        addCustomerOKButton.setText("OK");
        addCustomerOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerOKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerOKButton);

        addCustomerCancelButton.setText("Cancel");
        addCustomerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerCancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // In case you need to manage user input for the first name, insert your code for handling it in this section:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void addCustomerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_addCustomerCancelButtonActionPerformed

    private void addCustomerOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerOKButtonActionPerformed
        String firstName = firstNameTextField.getText().trim();
        String lastName = lastNameTextField.getText().trim();
        String phoneNumber = phoneNumberTextField.getText().trim();
        String initBalance = initBalanceTextField.getText().trim();
        BigDecimal balance = BigDecimal.ZERO;
        StringBuilder warnings = new StringBuilder();

        // TODO: Finish implementing this method to checks the input fields for the first name, last name,
        //  phone number, and initial balance. If any of these fields are empty or contain invalid data,
        //  a message dialog is displayed to alert the user about the input issues. Also display a warning
        //  message when a new customer is being created with a phone number that is already associated
        //  with an existing customer. If there are no warnings, a new Customer object is created with the
        //  provided first name, last name, and phone number. Then, based on the selected account type
        //  from a combo box (accountTypeComboBox), a corresponding type of bank account (CheckingAccount,
        //  SavingsAccount, or InvestmentAccount) is created and associated with the customer.
        //  The initial balance is set for the account if provided. Finally, the newly created customer
        //  is added to the customers list. After adding the customer, the TransferDialog is disposed,
        //  indicating the completion of the operation.

        // Validate required fields
        if (firstName.isEmpty()) {
            warnings.append("First name is required\n");
        }
        if (lastName.isEmpty()) {
            warnings.append("Last name is required\n");
        }
        if (phoneNumber.isEmpty()) {
            warnings.append("Phone number is required\n");
        }

        // Check for duplicate phone number
        for (Customer existingCustomer : customers) {
            if (existingCustomer.getPhoneNumber().equals(phoneNumber)) {
                warnings.append("A customer with this phone number already exists\n");
                break;
            }
        }

        // Validate initial balance
        try {
            if (!initBalance.isEmpty()) {
                balance = new BigDecimal(initBalance.trim());
                if (balance.compareTo(BigDecimal.ZERO) < 0) {
                    warnings.append("Initial balance cannot be negative\n");
                }
            }
        } catch (NumberFormatException e) {
            warnings.append("Invalid Initial balance format\n");
        }

        // If there are any warnings, show them and return
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    warnings.toString(),
                    "Input Warnings",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

       // Create new customer
       newlyAddedCustomer = new Customer(firstName, lastName, "", phoneNumber);

      // Create appropriate account type based on selection
      BankAccount account;
      String selectedAccountType = (String) accountTypeComboBox.getSelectedItem();

      switch (selectedAccountType) {
          case "Checking":
              account = new CheckingAccount(balance);
              break;
          case "Savings":
              account = new SavingsAccount(balance);
              break;
          case "Investment":
              account = new InvestmentAccount(balance);
              break;
          default:
              account = new CheckingAccount(balance);
      }

      // Add count to customer and customer to list
        newlyAddedCustomer.addBankAccount(account);
        customers.add(newlyAddedCustomer);

        // Close dialog
        this.dispose();
        
    }//GEN-LAST:event_addCustomerOKButtonActionPerformed

    public Customer getNewlyAddedCustomer()
    {
        return newlyAddedCustomer;
    }

    public JButton getAddCustomerCancelButton() {
        return addCustomerCancelButton;
    }

    public JButton getAddCustomerOKButton() {
        return addCustomerOKButton;
    }

    public JTextField getFirstNameTextField() {
        return firstNameTextField;
    }

    public JTextField getInitBalanceTextField() {
        return initBalanceTextField;
    }

    public JTextField getLastNameTextField() {
        return lastNameTextField;
    }

    public JTextField getPhoneNumberTextField() {
        return phoneNumberTextField;
    }

    public List<Customer> getCustomers() {
        return customers;
    }

    public JComboBox<String> getAccountTypeComboBox() {
        return accountTypeComboBox;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeComboBox;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton addCustomerCancelButton;
    private javax.swing.JButton addCustomerOKButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel initBalanceLabel;
    private javax.swing.JTextField initBalanceTextField;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    // End of variables declaration//GEN-END:variables
    
    // customized variable
    private List<Customer> customers;
    private Customer newlyAddedCustomer = null;

}
