/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.weber.cs3230.projects.finalproject;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author zycmm
 */
public class TransferDialog extends javax.swing.JDialog {

    /**
     * Creates new form TransferDialog
     */
    public TransferDialog(java.awt.Frame parent, boolean modal, BankAccount account, List<Customer> customers) {
        super(parent, modal);
        initComponents();
        this.account = account;
        this.customers = customers;
        
        setUpBankAccountRepository();
        fromAccountTextField.setText(String.valueOf(account.getAccountNumber()));
        setLocationRelativeTo(parent);
    }
    
    private void setUpBankAccountRepository()
    {
        List<BankAccount> accounts = new ArrayList<>();
        for(Customer customer : customers)
        {
            accounts.addAll(customer.getBankAccounts());
        }
        
        this.bankAccountRepository = new BankAccountRepository(accounts);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromAccountLabel = new javax.swing.JLabel();
        fromAccountTextField = new javax.swing.JTextField();
        toAccountLabel = new javax.swing.JLabel();
        toAccountTextField = new javax.swing.JTextField();
        transferAmountLabel = new javax.swing.JLabel();
        transferAmountTextField = new javax.swing.JTextField();
        transferOKButton = new javax.swing.JButton();
        transferCancelButton = new javax.swing.JButton();
        transferService = new TransferService((IBankAccountRepository) bankAccountRepository);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        fromAccountLabel.setText("From Account Number:");
        getContentPane().add(fromAccountLabel);
        getContentPane().add(fromAccountTextField);

        toAccountLabel.setText("To Account Number:");
        getContentPane().add(toAccountLabel);
        getContentPane().add(toAccountTextField);

        transferAmountLabel.setText("Transfer Amount");
        getContentPane().add(transferAmountLabel);
        getContentPane().add(transferAmountTextField);

        transferOKButton.setText("OK");
        transferOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferOKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferOKButton);

        transferCancelButton.setText("Cancel");
        transferCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transferCancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_transferCancelButtonActionPerformed

    // TODO: transfer a certain amount from one bank account to another

    private void transferOKButtonActionPerformed(java.awt.event.ActionEvent evt) {
        StringBuilder warnings = new StringBuilder();
        String toAccountStr = toAccountTextField.getText().trim();
        String transferAmountStr = transferAmountTextField.getText().trim();

        // Validate transfer amount
        if (transferAmountStr.isEmpty()) {
            warnings.append("Transfer amount is required");
            JOptionPane.showMessageDialog(this,
                    warnings.toString(),
                    "Transfer Warnings",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            BigDecimal amount = new BigDecimal(transferAmountStr);

            if (amount.compareTo(BigDecimal.ZERO) <= 0) {
                warnings.append("Transfer amount must be greater than zero");
                JOptionPane.showMessageDialog(this,
                        warnings.toString(),
                        "Transfer Warnings",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int toAccountNumber = Integer.parseInt(toAccountStr);
            BankAccount toAccount = bankAccountRepository.findByAccountNumber(toAccountNumber);

            if (toAccount.getAccountNumber() == account.getAccountNumber()) {
                warnings.append("Cannot transfer to the same account");
            } else {
                transferService = new TransferService((IBankAccountRepository)bankAccountRepository);
                try {
                    transferService.transfer(account.getAccountNumber(),
                            toAccount.getAccountNumber(),
                            amount);
                } catch (InsufficientFundException e) {
                    warnings.append("Insufficient funds: ").append(e.getMessage());
                } catch (NoSuchBankAccountException e) {
                    warnings.append("Account error: ").append(e.getMessage());
                }
            }
        } catch (NumberFormatException e) {
            warnings.append("Invalid number format");
        } catch (NoSuchBankAccountException e) {
            warnings.append("Account not found: ").append(e.getMessage());
        }

        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    warnings.toString(),
                    "Transfer Warnings",
                    JOptionPane.WARNING_MESSAGE);
        }

        this.dispose();
    }


    public JTextField getToAccountTextField() {
        return toAccountTextField;
    }

    public JTextField getTransferAmountTextField() {
        return transferAmountTextField;
    }

    public JButton getTransferOKButton() {
        return transferOKButton;
    }

    public JTextField getFromAccountTextField() {
        return fromAccountTextField;
    }

    public JButton getTransferCancelButton() {
        return transferCancelButton;
    }

    public void setBankAccountRepository(BankAccountRepository bankAccountRepository) {
        this.bankAccountRepository = bankAccountRepository;
    }

    public void setAccount(BankAccount account) {
        this.account = account;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromAccountLabel;
    private javax.swing.JTextField fromAccountTextField;
    private javax.swing.JLabel toAccountLabel;
    private javax.swing.JTextField toAccountTextField;
    private javax.swing.JLabel transferAmountLabel;
    private javax.swing.JTextField transferAmountTextField;
    private javax.swing.JButton transferCancelButton;
    private javax.swing.JButton transferOKButton;
    // End of variables declaration//GEN-END:variables
    
    private BankAccount account;
    private List<Customer> customers;
    private BankAccountRepository bankAccountRepository;

    private TransferService transferService;
}
