/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.weber.cs3230.projects.finalproject;

import javax.swing.*;
import java.math.BigDecimal;

/**
 *
 * @author zycmm
 */
public class WithdrawDialog extends JDialog {

    /**
     * Creates new form DepositDialog
     */
    public WithdrawDialog(java.awt.Frame parent, boolean modal, BankAccount account) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawAmountLabel = new JLabel();
        withdrawAmountTextField = new JTextField();
        withdrawOKButton = new JButton();
        withdrawCancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        withdrawAmountLabel.setText("Withdraw Amount:");
        getContentPane().add(withdrawAmountLabel);
        getContentPane().add(withdrawAmountTextField);

        withdrawOKButton.setText("OK");
        withdrawOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawOKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawOKButton);

        withdrawCancelButton.setText("Cancel");
        withdrawCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawCancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_withdrawCancelButtonActionPerformed

    private void withdrawOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawOKButtonActionPerformed
        StringBuilder warnings = new StringBuilder();

        // TODO: Finish implementing this method to withdraw a certain amount of money from a selected bank account.
        //  It checks if the withdrawal amount is empty. If it is, a warning message is appended to the warnings
        //  StringBuilder indicating that the withdrawal amount is empty. If the withdrawal amount is not empty,
        //  it's converted to a BigDecimal object for further processing. It checks if the withdrawal amount is
        //  greater than zero. If it is, it attempts to withdraw the specified amount from the account. If the
        //  withdrawal operation fails due to insufficient funds, the error message from the InsufficientFundException
        //  is appended to the warnings StringBuilder. After verifying the withdrawal amount and processing it,
        //  if there are any warnings (i.e., if the warnings StringBuilder is not empty), a message dialog is
        //  displayed to alert the user about any issues encountered during the withdrawal process.
        //  Finally, regardless of whether there are warnings or not, the current dialog (this) is disposed,
        //  indicating the completion of the withdrawal operation.





    }//GEN-LAST:event_withdrawOKButtonActionPerformed

    public JLabel getWithdrawAmountLabel() {
        return withdrawAmountLabel;
    }

    public JTextField getWithdrawAmountTextField() {
        return withdrawAmountTextField;
    }

    public JButton getWithdrawCancelButton() {
        return withdrawCancelButton;
    }

    public JButton getWithdrawOKButton() {
        return withdrawOKButton;
    }

    public BankAccount getAccount() {
        return account;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel withdrawAmountLabel;
    private JTextField withdrawAmountTextField;
    private JButton withdrawCancelButton;
    private JButton withdrawOKButton;
    // End of variables declaration//GEN-END:variables
    
    private BankAccount account;

}
